config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'
  resources :categories
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :blogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def is_admin?
    is_admin
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
  end

  def require_admin
    reditect_to blog_path unless current_user.is_admin?
  end

  around_action :switch_locale

  def switch_locale(&action)
    locale = cookies[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin, only: %w[new create edit update destroy]

  def index
    @categories = Category.all
    cate = params[:cate]
    @blogs = if !cate.nil?
               Blog.where(category_id: cate)
             else
               Blog.all
             end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.create(blog_params)

    if @blog.save
      redirect_to @blog
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])

    if @blog.update(blog_params)
      redirect_to @blog
    else
      render :edit
    end
  end

  def destroy
    p 'i hate ROR'
    @blog = Blog.find(params[:id])

    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_path, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content, :category_id)
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :require_admin, only: %w[new create edit update destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/blogs/_form.html.erb
<div class="flex-row d-flex justify-content-center">
    <div class="col-md-8">
        <div class="card mt-5">
            <div class="card-body">
                <%= form_for @blog do |f| %>
                <div class="form-group">
                    <%= f.label :title%>
                    <%= f.text_field :title, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= f.label :content %>
                    <%= f.text_area :content, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= f.select :category_id, Category.all.map { |c| [c.category, c.id] }  %>
                </div>

                <%= f.submit class: 'btn btn-outline-primary' do %>
                <%= t("Update Blog") %>
                <% end %>
                <%= link_to t("Back"), blogs_path, class: 'btn btn-outine-secondary' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/blogs/edit.html.erb
<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="row">
                <% @blogs.each do |blog| %>
                <div class="col-md-6">
                    <div class="card mt-3">
                        <div class="card-body">
                            <h3><%= link_to blog.title, blog_path(blog.id) %></h3>
                            <%= link_to t('View'), blog_path(blog.id), class: 'btn btn-primary' %>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>

        <div class="col-md-4 mt-3">
            <div class="card">
                <div class="card-header">
                    <%= t('Category') %>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        <% @categories.each do |category| %>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <%= link_to category.category, blogs_path(:cate => category.id) %>
                            <span class="badge badge-primary badge-pill"><%= category.blogs.count %></span>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/blogs/new.html.erb
<%= render 'form' %>

app/views/blogs/show.html.erb
<div class="container-fluid mt-3">

    <h1><%= t('Category') %>: <%= @blog.category.category %></h1>


    <h3><%= @blog.title %></h3>


    <p><%= @blog.content %></p>

    <% if current_user and current_user.is_admin? %>
    <%= link_to t('Edit'), edit_blog_path(@blog.id), class: 'btn btn-outline-primary' %>
    <%= link_to t('Delete'), blog_path(@blog), method: :delete, class: 'btn btn-outline-danger' %>
    <% end %>
    <%= link_to t('Back'), blogs_path, class: 'btn btn-outine-secondary' %>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('Editing Category') %></h1>

<%= render 'form', category: @category %>

<%= link_to t('Show'), @category %> |
<%= link_to t('Back'), categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('Categories') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('Category') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to t('Show'), category %></td>
        <td><%= link_to t('Edit'), edit_category_path(category) %></td>
        <td><%= link_to t('Delete'), category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('New Category'), new_category_path %> |
<%= link_to t('Main page'), blogs_path %>

app/views/categories/new.html.erb
<h1><%= t("New Category") %></h1>

<%= render 'form', category: @category %>

<%= link_to t('Back'), categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('Category') %>:</strong>
  <%= @category.category %>
</p>

<%= link_to t('Edit'), edit_category_path(@category) %> |
<%= link_to t('Back'), categories_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>BlogManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2    " crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">BlogManager</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-md-auto">
                <% if current_user and current_user.is_admin? %>
                <li class="nav-item active">
                    <%= link_to t("Create Blog"), new_blog_path, class: 'nav-link' %>
                </li>
                <li class="nav-item active">
                    <%= link_to t("Create Category"), new_category_path, class: 'nav-link' %>
                </li>
                <% end %>
                <li class="nav-item active">
                    <%= link_to t("Sign out"), destroy_user_session_path, method: :delete, class: 'nav-link' %>
                </li>
                <li>
                    <% if current_user %>
                    <%= current_user.email %>
                    <% end %>
                </li>
            </ul>
        </div>
        <div class="mt-5">
            <button class="btn btn-link js-switch-locale" data-locale="ru">Ru</button>
            <button class="btn btn-link js-switch-locale" data-locale="en">En</button>
        </div>
    </nav>
    <%= yield %>
</body>

</html>